\section{Thread\-Synch::Call\-Timeout\-Exception Class Reference}
\label{class_thread_synch_1_1_call_timeout_exception}\index{ThreadSynch::CallTimeoutException@{ThreadSynch::CallTimeoutException}}
thrown when a scheduled call times out.  


{\tt \#include $<$Call\-Scheduler\-Exceptions.h$>$}

\subsection*{Public Member Functions}
\begin{CompactItemize}
\item 
{\bf Call\-Timeout\-Exception} ()
\item 
{\bf Call\-Timeout\-Exception} (const char $\ast$const \&\_\-What)
\end{CompactItemize}


\subsection{Detailed Description}
thrown when a scheduled call times out. 



\subsection{Constructor \& Destructor Documentation}
\index{ThreadSynch::CallTimeoutException@{Thread\-Synch::Call\-Timeout\-Exception}!CallTimeoutException@{CallTimeoutException}}
\index{CallTimeoutException@{CallTimeoutException}!ThreadSynch::CallTimeoutException@{Thread\-Synch::Call\-Timeout\-Exception}}
\subsubsection{\setlength{\rightskip}{0pt plus 5cm}Thread\-Synch::Call\-Timeout\-Exception::Call\-Timeout\-Exception ()\hspace{0.3cm}{\tt  [inline]}}\label{class_thread_synch_1_1_call_timeout_exception_429fcf0febbad28e2a49eb6def726e88}


\index{ThreadSynch::CallTimeoutException@{Thread\-Synch::Call\-Timeout\-Exception}!CallTimeoutException@{CallTimeoutException}}
\index{CallTimeoutException@{CallTimeoutException}!ThreadSynch::CallTimeoutException@{Thread\-Synch::Call\-Timeout\-Exception}}
\subsubsection{\setlength{\rightskip}{0pt plus 5cm}Thread\-Synch::Call\-Timeout\-Exception::Call\-Timeout\-Exception (const char $\ast$const \& {\em \_\-What})\hspace{0.3cm}{\tt  [inline]}}\label{class_thread_synch_1_1_call_timeout_exception_afbcc3c79fc51b5ec8597a0d4f50973c}




The documentation for this class was generated from the following file:\begin{CompactItemize}
\item 
Thread\-Synch/{\bf Call\-Scheduler\-Exceptions.h}\end{CompactItemize}
